PREFIX vocab: <https://sharetrait.org/vocab/>

# ============================================================
# Query 7
# All species available in ShareTrait measured for the
# development trait.
# ============================================================

SELECT DISTINCT
  ?scientific_name
  ?genus_name
  ?trait_type

WHERE {
  ?measurement a vocab:Measurement ;
    vocab:hasTraitType      ?trait_type_iri ;
    vocab:hasIndividual ?individual .

  FILTER(?trait_type_iri = <https://sharetrait.org/concept/development>)
  BIND(STRAFTER(STR(?trait_type_iri), "concept/") AS ?trait_type)

  ?population a vocab:Population ;
    vocab:containsIndividual ?individual .

  ?taxonomy a vocab:Taxonomy ;
    vocab:labelsPopulation ?population .

  OPTIONAL { ?taxonomy vocab:hasScientificName ?scientific_name }
  OPTIONAL { ?taxonomy vocab:hasGenusName      ?genus_name }
}
