PREFIX vocab: <https://sharetrait.org/vocab/>

# ============================================================
# Query 5
# How many measurement values exist per Danio dataset,
# and what units are used for metabolic_rate traits?
# ============================================================

SELECT
  ?dataset_pk
  ?species_reported
  ?trait_type
  (COUNT(?trait_value) AS ?count_measurements)
  ?trait_unit

WHERE {
  ?taxonomy a vocab:Taxonomy ;
    vocab:hasGenusName ?genus_name .

  FILTER(?genus_name = "Danio")

  ?taxonomy vocab:labelsPopulation ?population .

  ?population a vocab:Population ;
    vocab:containsIndividual ?individual .

  ?dataset a vocab:Dataset ;
    vocab:describesPopulation ?population .

  ?measurement a vocab:Measurement ;
    vocab:hasIndividual ?individual ;
    vocab:hasTraitType      ?trait_type ;
    vocab:hasTraitValue     ?trait_value ;
    vocab:hasTraitUnit      ?trait_unit .

  BIND(STRAFTER(STR(?dataset), "dataset/") AS ?dataset_pk)

  OPTIONAL { ?population vocab:hasSpeciesReported ?species_reported }
}
GROUP BY ?dataset_pk ?species_reported ?trait_type ?trait_unit
