PREFIX vocab: <https://sharetrait.org/vocab/>

# ============================================================
# Query 2
# How many development trait measurements exist in ShareTrait
# for each genus?
# ============================================================

SELECT
  ?genus_name
  (COUNT(?trait_value) AS ?TRAIT_MEASURE)

WHERE {
  ?measurement a vocab:Measurement ;
    vocab:hasTraitType  ?trait_type_iri ;
    vocab:hasTraitValue ?trait_value ;
    vocab:hasIndividual ?individual .

  FILTER(?trait_type_iri = <https://sharetrait.org/concept/Development>)

  ?population a vocab:Population ;
    vocab:containsIndividual ?individual .

  ?taxonomy a vocab:Taxonomy ;
    vocab:labelsPopulation ?population ;
    vocab:hasGenusName    ?genus_name .
}
GROUP BY ?genus_name
ORDER BY DESC(?TRAIT_MEASURE)
